### ISSUE TITLE
A suggestion on making txtgen more extensible 

### ISSUE THREAD

**Issue by atishbits** [ndaidong/txtgen#34]
Hi, this is a really useful tool! 
The current list of nouns and adjectives included in txtgen is very small. There are multiple resources to get richer set of these such as the nltk corpus of wordnet which can be leveraged by consumers of txtgen to producer a larger variety of english text. 
I think it will be great if the author expose a way (files?) for users to initialize txtgen with their own list of nouns and adjectives. That way, with a longer list of nouns and adjectives, txtgen would produce lesser frequency of duplicate sentences.

Thanks
Atish

**Comment by ndaidong** [comment]
@atishbits thank you for your opinion. Do you mean the methods `addTemplates()`,  `addAdjectives()` and   `addNouns()` aren't easy to use? If so, I'm going to consider a more flexible way to do that.

**Comment by atishbits** [comment]
@ndaidong aah. I guess I missed those methods when I used this tool! I was searching for a config file in the project to see if I could supply a path to a file containing a larger list of nouns/adjectives. In the hindsight, the provided methods should work just fine! Thanks.
