### ISSUE TITLE
Feature to focus on subjects across sentences

### ISSUE THREAD

**Issue by jackomix** [ndaidong/txtgen#56]
My suggestion is the ability to have "subjects", or recurring nouns across sentences. Currently in a generated paragraph, each sentence has no relation to each other. To make it feel more coherent, I think subjects would help. You could also try talking about multiple subjects, perhaps you could have templates for talking about the different subjects, like sentences structuring like "ABAB" (Talk about A, then B, then A again, then B again), or "AABB", etc.

By the way great library! Just wanted to give out a suggestion. 👍

**Comment by ndaidong** [comment]
thank you for your idea @jackomix 
I've worked with some Text Generators using NLP that are able to make meaningful documents. However the purpose of this library is try to generate the random (and non-sense) text, so that people could not guess the next sentence.
