### ISSUE TITLE
Extending functionality and types

### ISSUE THREAD

**Issue by ngregrichardson** [ndaidong/txtgen#69]
I used Sentencer for a project a long time ago and wanted to use a slightly updated version (plus, this has better TypeScript support), so I love seeing that Sentencer inspired this!

For my use case, I always want to generate a specific template. I _can_ achieve this by using `setTemplates`, but that wasn't obvious at first, and I feel like there would be room to improve that. I was thinking of adding functionality to support this:

```ts
const firstPhrase = generate('{{ adjective }} {{ noun }}');

const secondPhrase = generate('{{ adjective }} {{ noun }}!!!');
```

instead of 

```ts
setTemplates(['{{ adjective }} {{ noun }}']);
const firstPhrase = sentence();

setTemplates(['{{ adjective }} {{ noun }}!!!']);
const secondPhrase = sentence();
```

The functionality basically already exists, I would just want to clean it up and export it from the library. Along with this, I would love something like `TxtGenOptions` to be added as an optional parameter to the generation functions defined something like

```ts
type TxtgenOptions = {
    addPunctuation?: boolean, // This would probably be exclusive to sentence generation
    addPhrases?: boolean // To allow removing the beginning phrases
}
```

I see that the exported functions like `sentence` actually takes a boolean to disable the additional phrases, but those aren't included in the types.

I would be excited to work on these changes if you'd accept a PR for it in a little bit. Let me know what you think!

**Comment by ndaidong** [comment]
@ngregrichardson sorry for late reply, and I don't have much experience with TypeScript. I would be very grateful if you could make a PR.

**Comment by ngregrichardson** [comment]
No problem! I'll probably work on it this weekend and get a PR to you.
